backend:
  name: git-gateway
  branch: main
  identity_url: 'https://jpartynen.netlify.app/.netlify/identity'

media_folder: 'static/media'
public_folder: '/media'

collections:
  - name: 'gigs'
    label: 'Gigs'
    folder: 'content/gigs'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'uuid', default: 'uuidv4' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Lineup', name: 'lineup', widget: 'string' }
      - { label: 'Venue', name: 'venue', widget: 'string' }
      - { label: 'City', name: 'city', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Time', name: 'time', widget: 'string', required: false }
