backend:
  name: git-gateway
  branch: main # Git branch to commit to

media_folder: 'public/images' # Folder in your repo for uploaded media
public_folder: '/images' # Public path used in HTML

media_library:
  name: uploadcare
  config:
    publicKey: 'demopublickey' # For testing, you can replace with your own service later

collections:
  - name: 'gigs'
    label: 'Gigs'
    folder: 'content/gigs' # Folder in your repo for gigs JSON
    create: true
    slug: '{{slug}}'
    format: json
    fields:
      - { label: 'ID', name: 'id', widget: 'uuid', default: 'uuidv4' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Lineup', name: 'lineup', widget: 'string' }
      - { label: 'Venue', name: 'venue', widget: 'string' }
      - { label: 'City', name: 'city', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Time', name: 'time', widget: 'string', required: false }
